# -*- coding: utf-8 -*-
"""Copy of project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eB0XdXcOCG0PAw9o-Mguz3Cqx9hwNA7p
"""

import requests
import pandas as pd
import sqlite3
import json
import matplotlib.pyplot as plt
import os

url = ' https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc&per_page=100'
response = requests.get(url)
print("API Status Code:", response.status_code)

data = response.json()
data['items'] [0]

df = pd.DataFrame(data['items'])
df.head()

df.info()

df.shape

df.columns

essential_columns = [
    "id", "name", "full_name", "description", "html_url",
    "stargazers_count", "watchers_count", "forks_count",
    "open_issues_count", "size", "score", "language",
    "visibility", "topics", "created_at", "updated_at", "pushed_at"
]


df = df[essential_columns]
df.shape

df.columns

df = df.rename(columns={'stargazers_count': 'stargazers' ,
                        'watchers_count' : 'watchers',
                        'forks_count' : 'forks',
                        'open_issues_count' : 'open_issues',


                        })

df.columns

df.to_csv('github_projects.csv', index=False)

!pip install ipython-sql==0.5.0 prettytable==3.9.0

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql
# %config SqlMagic.style = 'PLAIN_COLUMNS'
# %sql sqlite:///library.db

repositories = pd.read_csv("github_projects.csv")
 repositories.to_sql("repositories", "sqlite:///library.db", if_exists="replace", index=False)

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM repositories
# where stargazers > 10000;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
#     FROM Repositories
#     WHERE full_name LIKE '%machine%';

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM repositories
# WHERE language='Python' AND visibility = 'public';
#

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM repositories
# WHERE language = 'C++' OR  name = 'tensorflow' ;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
#   FROM repositories
#   WHERE NOT name = 'transformers';

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM repositories
#  ORDER BY  stargazers ASC ;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT *
# FROM repositories
#  ORDER BY  stargazers DESC
# LIMIT 10  ;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT COUNT(*)
# FROM repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT AVG(stargazers)
# FROM repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT MAX(stargazers)
# FROM repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT MIN(stargazers)
# FROM repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT SUM(stargazers)
# FROM repositories;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT language AS programing language
# group by language

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT language, COUNT(*) AS repo_count
# FROM repositories
# GROUP BY language;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT language, COUNT(*) AS repo_count
# FROM repositories
# GROUP BY language
# HAVING COUNT(*) > 5;

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT full_name, stargazers
# FROM repositories
#  ORDER BY stargazers DESC LIMIT 10

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# SELECT SUBSTR(created_at, 1, 4) as year,
# COUNT(*) as count
# FROM repositories
# GROUP BY year
# ORDER BY year;

df= pd.read_csv('github_projects.csv')
df.head()

plt.figure(figsize=(10, 5))
plt.bar(df['full_name'][::-1], df['stargazers'][::-1], color='skyblue')
plt.xlabel('Stargazers')
plt.title('Top 10 Most Popular Repositories')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(df['created_at'], df['pushed_at'], marker='o', color='green', linewidth=2)
plt.xlabel('created_at')
plt.ylabel('Number of Repositories Created')
plt.title('Repository Creation Trends Over Time')
plt.grid(True)
plt.tight_layout()
plt.show()

""". **Important Patterns (الأنماط المهمة)**
تركز اللغات (Language Concentration): نلاحظ أن معظم المشاريع والمستودعات تتركز في لغات برمجة معينة ومعروفة مثل Python و JavaScript، مما يشير إلى شعبيتها الطاغية وهيمنتها على مجتمع المطورين مقارنة باللغات الأخرى.

تفاوت النجوم (Star Distribution): هناك نمط واضح يسمى "Power Law" أو التوزيع غير المتكافئ؛ حيث تحظى نسبة ضئيلة جداً من المستودعات بعدد هائل وفلكي من النجوم (Stargazers)، بينما تمتلك الغالبية العظمى من المستودعات عددًا قليلًا جدًا أو معدومًا من النجوم.

. **Trends in the Data (الاتجاهات في البيانات)**
النمو الزمني (Growth Over Time): يُظهر الرسم البياني الزمني تصاعداً ملحوظاً في عدد المستودعات التي يتم إنشاؤها عاماً بعد عام، مما يعكس النمو المستمر وسرعة تطور مجتمع البرمجة المفتوحة المصدر (Open Source).

هيمنة المشاريع البارزة: المستودعات التي تتخطى حاجز الـ 10,000 نجمة تشهد عادةً نشاطًا تفاعليًا وتحديثات مستمرة مقارنة بالمشاريع المهجورة.

. **Useful Insights Answering Business Questions (رؤى مفيدة تجيب على أسئلة العمل)**
الاهتمام المجتمعي: يتركز اهتمام المطورين والمستخدمين بشكل مكثف على المشاريع التي تقدم حلولاً في مجالات الذكاء الاصطناعي وتعلم الآلة (والتي تظهر بوضوح عند البحث بكلمات مثل machine).

شروط الشعبية: المشاريع التي تحقق نجاحاً جماهيرياً كبيرًا غالباً ما تكون عامة (visibility = 'public') ومكتوبة بلغات سهلة ومستخدمة على نطاق واسع.
"""

